# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sec\PycharmProjects\KSJr3DF-Project\GUI\ui_dir\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import GUI.dlg0_signup_evt, GUI.dlg1_menu1_evt, GUI.dlg2_menu2_evt, GUI.dlg3_menu3_evt, GUI.dlg4_menu4_evt
import GUI.login, GUI.signup, GUI.topology

class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\sec\\PycharmProjects\\KSJr3DF-Project\\GUI\\ui_dir\\../icon/dron.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.WS_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.WS_scrollArea.setGeometry(QtCore.QRect(10, 60, 100, 310))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WS_scrollArea.sizePolicy().hasHeightForWidth())
        self.WS_scrollArea.setSizePolicy(sizePolicy)
        self.WS_scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WS_scrollArea.setWidgetResizable(True)
        self.WS_scrollArea.setObjectName("WS_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 308))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.WS_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Snapshot_scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.Snapshot_scrollArea.setGeometry(QtCore.QRect(104, 60, 142, 310))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Snapshot_scrollArea.sizePolicy().hasHeightForWidth())
        self.Snapshot_scrollArea.setSizePolicy(sizePolicy)
        self.Snapshot_scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Snapshot_scrollArea.setWidgetResizable(True)
        self.Snapshot_scrollArea.setObjectName("Snapshot_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 140, 308))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.Snapshot_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.Menu1_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Menu1_pushbutton.setGeometry(QtCore.QRect(0, 0, 60, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu1_pushbutton.sizePolicy().hasHeightForWidth())
        self.Menu1_pushbutton.setSizePolicy(sizePolicy)
        self.Menu1_pushbutton.setObjectName("Menu1_pushbutton")
        self.Menu2_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Menu2_pushButton.setGeometry(QtCore.QRect(60, 0, 60, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu2_pushButton.sizePolicy().hasHeightForWidth())
        self.Menu2_pushButton.setSizePolicy(sizePolicy)
        self.Menu2_pushButton.setObjectName("Menu2_pushButton")
        self.Menu3_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Menu3_pushButton.setGeometry(QtCore.QRect(120, 0, 60, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu3_pushButton.sizePolicy().hasHeightForWidth())
        self.Menu3_pushButton.setSizePolicy(sizePolicy)
        self.Menu3_pushButton.setObjectName("Menu3_pushButton")
        self.Menu4_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Menu4_pushButton.setGeometry(QtCore.QRect(180, 0, 60, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu4_pushButton.sizePolicy().hasHeightForWidth())
        self.Menu4_pushButton.setSizePolicy(sizePolicy)
        self.Menu4_pushButton.setObjectName("Menu4_pushButton")
        self.Menu5_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Menu5_pushButton.setGeometry(QtCore.QRect(240, 0, 60, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu5_pushButton.sizePolicy().hasHeightForWidth())
        self.Menu5_pushButton.setSizePolicy(sizePolicy)
        self.Menu5_pushButton.setObjectName("Menu5_pushButton")
        self.Preview_Label = QtWidgets.QLabel(self.centralwidget)
        self.Preview_Label.setGeometry(QtCore.QRect(270, 60, 310, 310))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Preview_Label.sizePolicy().hasHeightForWidth())
        self.Preview_Label.setSizePolicy(sizePolicy)
        self.Preview_Label.setText("")
        self.Preview_Label.setPixmap(QtGui.QPixmap("C:\\Users\\sec\\PycharmProjects\\KSJr3DF-Project\\GUI\\ui_dir\\../icon/back.png"))
        self.Preview_Label.setScaledContents(True)
        self.Preview_Label.setObjectName("Preview_Label")
        self.Top_frame = QtWidgets.QFrame(self.centralwidget)
        self.Top_frame.setGeometry(QtCore.QRect(0, 0, 750, 40))
        self.Top_frame.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"background-color: rgb(184, 184, 184);")
        self.Top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_frame.setObjectName("Top_frame")
        self.Right_frame = QtWidgets.QFrame(self.centralwidget)
        self.Right_frame.setGeometry(QtCore.QRect(600, 40, 160, 330))
        self.Right_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Right_frame.setObjectName("Right_frame")
        self.Active_scrollArea = QtWidgets.QScrollArea(self.Right_frame)
        self.Active_scrollArea.setGeometry(QtCore.QRect(10, 20, 130, 270))
        self.Active_scrollArea.setStyleSheet("")
        self.Active_scrollArea.setWidgetResizable(True)
        self.Active_scrollArea.setObjectName("Active_scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 128, 268))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.Active_scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.Active_pushButton = QtWidgets.QPushButton(self.Right_frame)
        self.Active_pushButton.setGeometry(QtCore.QRect(10, 295, 130, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Active_pushButton.sizePolicy().hasHeightForWidth())
        self.Active_pushButton.setSizePolicy(sizePolicy)
        self.Active_pushButton.setStyleSheet("background-color: rgb(51, 160, 255);")
        self.Active_pushButton.setObjectName("Active_pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(102, 60, 20, 310))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Right_frame.raise_()
        self.Top_frame.raise_()
        self.WS_scrollArea.raise_()
        self.Snapshot_scrollArea.raise_()
        self.Menu1_pushbutton.raise_()
        self.Menu2_pushButton.raise_()
        self.Menu3_pushButton.raise_()
        self.Menu4_pushButton.raise_()
        self.Menu5_pushButton.raise_()
        self.Preview_Label.raise_()
        self.line.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "General 5ho"))
        self.Menu1_pushbutton.setText(_translate("MainWindow", "menu1"))
        self.Menu2_pushButton.setText(_translate("MainWindow", "menu2"))
        self.Menu3_pushButton.setText(_translate("MainWindow", "menu3"))
        self.Menu4_pushButton.setText(_translate("MainWindow", "menu4"))
        self.Menu5_pushButton.setText(_translate("MainWindow", "menu5"))
        self.Active_pushButton.setText(_translate("MainWindow", "Active"))

    def login(self):
        loginDlg = QtWidgets.QDialog()
        loginui = GUI.login.Ui_Dialog()
        loginui.setupUi(loginDlg)
        loginDlg.show()
        loginDlg.exec_()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    #ui.login()
    MainWindow.show()
    sys.exit(app.exec_())
