# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sec\PycharmProjects\KSJr3DF-Project\GUI\ui_dir\Topology1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        super(Ui_Dialog, self).__init__()
        self.setupUi(Dialog)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(950, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\sec\\PycharmProjects\\KSJr3DF-Project\\GUI\\ui_dir\\../icon/dron.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.Right_frame = QtWidgets.QFrame(Dialog)
        self.Right_frame.setGeometry(QtCore.QRect(730, 20, 210, 710))
        self.Right_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Right_frame.setObjectName("Right_frame")
        self.Finish_pushButton_2 = QtWidgets.QPushButton(self.Right_frame)
        self.Finish_pushButton_2.setGeometry(QtCore.QRect(10, 670, 190, 30))
        self.Finish_pushButton_2.setStyleSheet("background-color: rgb(51, 160, 255);\n"
"color: rgb(255, 255, 255);")
        self.Finish_pushButton_2.setObjectName("Finish_pushButton_2")
        self.Toolbox_scrollArea_2 = QtWidgets.QScrollArea(self.Right_frame)
        self.Toolbox_scrollArea_2.setGeometry(QtCore.QRect(10, 465, 190, 150))
        self.Toolbox_scrollArea_2.setStyleSheet("background-color: rgb(209, 212, 205);")
        self.Toolbox_scrollArea_2.setWidgetResizable(True)
        self.Toolbox_scrollArea_2.setObjectName("Toolbox_scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 188, 148))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.Toolbox_scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.First_scrollArea_2 = QtWidgets.QScrollArea(self.Right_frame)
        self.First_scrollArea_2.setGeometry(QtCore.QRect(10, 30, 190, 100))
        self.First_scrollArea_2.setStyleSheet("background-color: rgb(209, 212, 205);")
        self.First_scrollArea_2.setWidgetResizable(True)
        self.First_scrollArea_2.setObjectName("First_scrollArea_2")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 188, 98))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 20, 96, 19))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 40, 96, 19))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_6)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 60, 96, 19))
        self.checkBox_12.setObjectName("checkBox_12")
        self.First_scrollArea_2.setWidget(self.scrollAreaWidgetContents_6)
        self.line_4 = QtWidgets.QFrame(self.Right_frame)
        self.line_4.setGeometry(QtCore.QRect(10, 140, 190, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.First_Label_2 = QtWidgets.QLabel(self.Right_frame)
        self.First_Label_2.setGeometry(QtCore.QRect(10, 10, 190, 25))
        self.First_Label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.First_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.First_Label_2.setObjectName("First_Label_2")
        self.Second_Label_2 = QtWidgets.QLabel(self.Right_frame)
        self.Second_Label_2.setGeometry(QtCore.QRect(10, 150, 190, 25))
        self.Second_Label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Second_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Second_Label_2.setObjectName("Second_Label_2")
        self.Third_Label_2 = QtWidgets.QLabel(self.Right_frame)
        self.Third_Label_2.setGeometry(QtCore.QRect(10, 295, 190, 25))
        self.Third_Label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Third_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Third_Label_2.setObjectName("Third_Label_2")
        self.Second_scrollArea_2 = QtWidgets.QScrollArea(self.Right_frame)
        self.Second_scrollArea_2.setGeometry(QtCore.QRect(10, 175, 190, 100))
        self.Second_scrollArea_2.setStyleSheet("background-color: rgb(209, 212, 205);")
        self.Second_scrollArea_2.setWidgetResizable(True)
        self.Second_scrollArea_2.setObjectName("Second_scrollArea_2")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 188, 98))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 10, 96, 19))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 30, 96, 19))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_7)
        self.checkBox_15.setGeometry(QtCore.QRect(10, 50, 96, 19))
        self.checkBox_15.setObjectName("checkBox_15")
        self.Second_scrollArea_2.setWidget(self.scrollAreaWidgetContents_7)
        self.Third_scrollArea_2 = QtWidgets.QScrollArea(self.Right_frame)
        self.Third_scrollArea_2.setGeometry(QtCore.QRect(10, 320, 190, 100))
        self.Third_scrollArea_2.setStyleSheet("background-color: rgb(209, 212, 205);")
        self.Third_scrollArea_2.setWidgetResizable(True)
        self.Third_scrollArea_2.setObjectName("Third_scrollArea_2")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 188, 98))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.checkBox_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_8)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 30, 96, 19))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_8)
        self.checkBox_17.setGeometry(QtCore.QRect(10, 10, 96, 19))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_8)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 50, 96, 19))
        self.checkBox_18.setObjectName("checkBox_18")
        self.Third_scrollArea_2.setWidget(self.scrollAreaWidgetContents_8)
        self.line_5 = QtWidgets.QFrame(self.Right_frame)
        self.line_5.setGeometry(QtCore.QRect(10, 285, 190, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.Toolbox_Label_2 = QtWidgets.QLabel(self.Right_frame)
        self.Toolbox_Label_2.setGeometry(QtCore.QRect(10, 440, 190, 25))
        self.Toolbox_Label_2.setStyleSheet("background-color: rgb(51, 160, 255);\n"
"color: rgb(255, 255, 255);")
        self.Toolbox_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Toolbox_Label_2.setObjectName("Toolbox_Label_2")
        self.line_6 = QtWidgets.QFrame(self.Right_frame)
        self.line_6.setGeometry(QtCore.QRect(10, 430, 190, 3))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 710, 710))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "General 5ho"))
        self.Finish_pushButton_2.setText(_translate("Dialog", "완료"))
        self.checkBox_10.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_11.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_12.setText(_translate("Dialog", "CheckBox"))
        self.First_Label_2.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.First_Label_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.First_Label_2.setText(_translate("Dialog", "1"))
        self.Second_Label_2.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.Second_Label_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.Second_Label_2.setText(_translate("Dialog", "2"))
        self.Third_Label_2.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.Third_Label_2.setWhatsThis(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.Third_Label_2.setText(_translate("Dialog", "3"))
        self.checkBox_13.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_14.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_15.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_16.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_17.setText(_translate("Dialog", "CheckBox"))
        self.checkBox_18.setText(_translate("Dialog", "CheckBox"))
        self.Toolbox_Label_2.setText(_translate("Dialog", "도구상자"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    Dialog.show()
    sys.exit(app.exec_())
